### ISSUE TITLE
Update to v2

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-galileo#1]
@netarc Can you tackle updating this library to v2 of the API before APIv1 is deprecated (on April 24th)?

cc: @bradybd @Adonya

**Comment by netarc** [comment]
I will get this switched over today.

**Comment by kristinpeterson** [comment]
@netarc AWESOME! :joy_cat:

**Comment by netarc** [comment]
@kristinpeterson I updated to v2, can you give things a look over?

**Comment by kristinpeterson** [comment]
@netarc Looks good!  Thanks for churning this out so quickly!
